### ISSUE TITLE
This repository spoils CryptoHack

### ISSUE THREAD

**Issue by GiacomoPope** [mritunjaya1568/Cryptography-resources#2]
To avoid people copy pasting solutions and ruining their experience of the site, we ask people to keep their solutions private. If you want to share your solution publicaly, we have a "solutions" tab on every challenge which you can contribute to.

**Comment by mritunjaya1568** [comment]
Sorry man. I just created this repository in order to store my programming work. Never thought people would die hard search for solutions to look at my inactive and unpopular repo. It was private earlier but made public because of file uploading size issue ...

I will make it private again. Once again sorry for the trouble.
